### ISSUE TITLE
counsel-M-x?

### ISSUE THREAD

**Issue by kaushalmodi** [purcell/ivy-smex#1]
Hi Steve,

I use [`counsel-M-x`](https://github.com/abo-abo/swiper/blob/04c21608eae49651a524e2f7c15c5ee1a1a74dc8/counsel.el#L652) from the `counsel` package which basically is enhanced `M-x`, and uses `ivy` and `smex`.

This package has many other commands which use `ivy` as backend.. like `counsel-describe-function`, `counsel-describe-variable`, etc.

![image](https://cloud.githubusercontent.com/assets/3578197/18025164/748a826e-6bee-11e6-80b6-5f5c7915ab05.png)

**Comment by kaushalmodi** [comment]
Looks like you already reverted it .. sorry, I was just going through the Melpa updates in my RSS reader.
https://github.com/melpa/melpa/commit/d493ca0e1331fbd64924d02fe5c1dbc588d7db51

**Comment by purcell** [comment]
Thanks for this note! Hey, what's that theme? Not only does it look good, but I'm fascinated by the fact that the blue background of `counsel-org-tag-agenda` shows through the grey highlight of `couns`. What is this magic?

**Comment by kaushalmodi** [comment]
> Thanks for this note! Hey, what's that theme? N

It's [my fork of the smyx theme](https://github.com/kaushalmodi/smyx) :)

> Not only does it look good, but I'm fascinated by the fact that the blue background of counsel-org-tag-agenda shows through the grey highlight of couns. What is this magic?

I cannot take credit for that magic! That's all @abo-abo and his [`colir`](https://github.com/abo-abo/swiper/blob/master/colir.el) library. Here's one of his [blog posts](http://oremacs.com/2015/04/28/blending-faces/) on this topic.
